AWSTemplateFormatVersion: "2010-09-09"
Description: "This template deploys a SQS queue with notifications from S3"
Parameters:
  QName:
    Type: String
  Visibility:
    Type: Number
    Default: 60
  Delay:
    Type: Number
    Default: 0
    MinValue: 0
    MaxValue: 900
  MaxSize:
    Type: Number
    Default: 262144
    MinValue: 1024
    MaxValue: 262144
  KMSKey:
    Type: String
    Default: AWS::NoValue
  KmsDataReusePeriod:
    Type: Number
    Default: 300
    MinValue: 60
    MaxValue: 86400
  RetentionPeriod:
    Type: Number
    Default: 345600
    MinValue: 60
    MaxValue: 1209600
  ReceiveMessageWaitTime:
    Type: Number
    Default: 0
    MinValue: 0
    MaxValue: 20
  UseDeadLetterQueue:
    Type: String
    Default: false
    AllowedValues:
      - true
      - false
  MaxReceive:
    Type: Number
    Default: 5
  DeadLetterQName:
    Type: String
    Default: AWS::NoValue
Conditions:
  CreateDLQ: !Equals [ !Ref UseDeadLetterQueue, true ]
Resources:
  MyQueue:
    Type: AWS::SQS::Queue
    Properties:
      DelaySeconds: 
        Ref: Delay
      KmsMasterKeyId: 
        Ref: KMSKey
      KmsDataKeyReusePeriodSeconds: 
        Ref: KmsDataReusePeriod
      MaximumMessageSize: 
        Ref: MaxSize
      MessageRetentionPeriod: 
        Ref: RetentionPeriod
      QueueName: 
        Ref: QName
      ReceiveMessageWaitTimeSeconds: 
        Ref: ReceiveMessageWaitTime
      RedrivePolicy:
        !If 
          - CreateDLQ
          -
            deadLetterTargetArn: 
              Fn::GetAtt: 
                - "MyDeadLetterQueue"
                - "Arn"
            maxReceiveCount: 
              Ref: MaxReceive
          - !Ref "AWS::NoValue"
      VisibilityTimeout: 
        Ref: Visibility
  MyDeadLetterQueue: 
    Condition: CreateDLQ
    Type: AWS::SQS::Queue
    Properties:
      QueueName:
        Ref: DeadLetterQName
Outputs: 
  QueueURL: 
    Description: "URL of newly created SQS Queue"
    Value: 
      Ref: "MyQueue"
  QueueARN: 
    Description: "ARN of newly created SQS Queue"
    Value: 
      Fn::GetAtt: 
        - "MyQueue"
        - "Arn"
  QueueName: 
    Description: "Name newly created SQS Queue"
    Value: 
      Fn::GetAtt: 
        - "MyQueue"
        - "QueueName"
  DeadLetterQueueURL:
    Description: "URL of the dead letter queue"
    Condition: CreateDLQ
    Value: 
      Ref: "MyDeadLetterQueue"
  DeadLetterQueueARN: 
    Description: "ARN of the dead letter queue"
    Condition: CreateDLQ
    Value: 
      Fn::GetAtt: 
        - "MyDeadLetterQueue"
        - "Arn"
