AWSTemplateFormatVersion: "2010-09-09"
Description: "This template deploys a SQS queue with notifications from S3"
Parameters:
  AppName:
    Type: String
  Environment:
    Type: String
  Visibility:
    Type: Number
    Default: 60
  Delay:
    Type: Number
    Default: 0
    MinValue: 0
    MaxValue: 900
  MaxSize:
    Type: Number
    Default: 262144
    MinValue: 1024
    MaxValue: 262144
  KMSKey:
    Type: String
    Default: AWS::NoValue
  KmsDataReusePeriod:
    Type: Number
    Default: 300
    MinValue: 60
    MaxValue: 86400
  RetentionPeriod:
    Type: Number
    Default: 345600
    MinValue: 60
    MaxValue: 1209600
  ReceiveMessageWaitTime:
    Type: Number
    Default: 0
    MinValue: 0
    MaxValue: 20
  UseDeadLetterQueue:
    Type: String
    Default: false
    AllowedValues:
      - true
      - false
  MaxReceive:
    Type: Number
    Default: 5
Conditions:
  CreateDLQ: !Equals [ !Ref UseDeadLetterQueue, true ]
Resources:

  SourceBucket:
    Type: AWS::S3::Bucket
    DependsOn:
      - MyQueue
    Properties:
      BucketName: !Join [ "-", [ !Ref AppName, !Ref Environment ] ]
      NotificationConfiguration:
        QueueConfigurations:
          - Event: s3:ObjectCreated:*
            Queue:
              Fn::GetAtt: 
                - "MyQueue"
                - "Arn"
            
  MyQueue:
    Type: AWS::SQS::Queue
    Properties:
      DelaySeconds: 
        Ref: Delay
      KmsMasterKeyId: 
        Ref: KMSKey
      KmsDataKeyReusePeriodSeconds: 
        Ref: KmsDataReusePeriod
      MaximumMessageSize: 
        Ref: MaxSize
      MessageRetentionPeriod: 
        Ref: RetentionPeriod
      QueueName: 
        Ref: !Join [ "-", [ !Ref AppName, !Ref Environment ] ]
      ReceiveMessageWaitTimeSeconds: 
        Ref: ReceiveMessageWaitTime
      RedrivePolicy:
        !If 
          - CreateDLQ
          -
            deadLetterTargetArn: 
              Fn::GetAtt: 
                - "MyDeadLetterQueue"
                - "Arn"
            maxReceiveCount: 
              Ref: MaxReceive
          - !Ref "AWS::NoValue"
      VisibilityTimeout: 
        Ref: Visibility
        
  MyDeadLetterQueue: 
    Condition: CreateDLQ
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Join [ "-", [ !Ref AppName, !Ref Environment,  DLQ] ]

  QueuePolicy:
    Type: AWS::SQS::QueuePolicy
    DependsOn:
      - MyQueue
    Properties: 
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: '*'
            Action:
              - SQS:SendMessage
            # Target a wildcard resource name based on the same format as QueueName
            Resource: 
              Fn::GetAtt: 
                - "MyQueue"
                - "Arn"
            Condition:
              ArnLike:
                # Static BucketName used to avoid circular dependency with S3 bucket
                aws:SourceArn: !Join [ "", ["arn:aws:s3:*:*:", !Join [ "-", [ !Ref AppName, !Ref Environment ] ] ] ]
      Queues:
        - Fn::GetAtt: 
            - "MyDeadLetterQueue"
            - "Arn"

Outputs: 
  QueueURL: 
    Description: "URL of newly created SQS Queue"
    Value: 
      Ref: "MyQueue"
  QueueARN: 
    Description: "ARN of newly created SQS Queue"
    Value: 
      Fn::GetAtt: 
        - "MyQueue"
        - "Arn"
  QueueName: 
    Description: "Name newly created SQS Queue"
    Value: 
      Fn::GetAtt: 
        - "MyQueue"
        - "QueueName"
  DeadLetterQueueURL:
    Description: "URL of the dead letter queue"
    Condition: CreateDLQ
    Value: 
      Ref: "MyDeadLetterQueue"
  DeadLetterQueueARN: 
    Description: "ARN of the dead letter queue"
    Condition: CreateDLQ
    Value: 
      Fn::GetAtt: 
        - "MyDeadLetterQueue"
        - "Arn"
