AWSTemplateFormatVersion: "2010-09-09"
Description: "This template deploys a S3 Bucket"
Parameters:
  AppName:
    Type: String
  Environment:
    Type: String
  ACL:
    Type: String
    Default: AWS::NoValue
    AllowedValues:
      - AuthenticatedRead
      - AwsExecRead
      - BucketOwnerRead
      - BucketOwnerFullControl
      - LogDeliveryWrite
      - Private
      - PublicRead
      - PublicReadWrite
   AccelerateStatus:
    Type: String
    Default: AWS::NoValue
    
  
Resources:
  MyBucket:
    Type: AWS::S3::Bucket
    Properties: 
      AccessControl: 
        Ref: ACL
      AccelerateConfiguration:
        AccelerationStatus: !Ref AccelerateStatus:
      AnalyticsConfigurations:
        - AnalyticsConfiguration
      BucketEncryption: 
        BucketEncryption
      BucketName: !Join [ "-", [ !Ref AppName, !Ref Environment ] ]
      CorsConfiguration:
        CorsConfiguration
      InventoryConfigurations:
        - InventoryConfiguration 
      LifecycleConfiguration:
        LifecycleConfiguration
      LoggingConfiguration:
        LoggingConfiguration
      MetricsConfigurations: 
        - MetricsConfiguration
      NotificationConfiguration:
        NotificationConfiguration
      PublicAccessBlockConfiguration: 
        PublicAccessBlockConfiguration
      ReplicationConfiguration:
        ReplicationConfiguration
      VersioningConfiguration:
        VersioningConfiguration
      WebsiteConfiguration:
        WebsiteConfiguration