AWSTemplateFormatVersion: "2010-09-09"
Description: "This template deploys a S3 Bucket"
Parameters:
  AppName:
    Type: String
  Environment:
    Type: String
  Region:
    Type: String
  AccountID:
    Type: String
  QueueName:
    Type: String
Resources:
  MyBucket:
    Type: AWS::S3::Bucket
    Properties: 
      BucketName: !Join [ "-", [ !Ref AppName, !Ref Environment ] ]
      NotificationConfiguration:
        QueueConfigurations:
          - Event: s3:ObjectCreated:*
            Queue: arn:aws:sqs:eu-west-1:838188513541:sqsnotifications-sndbx
            #!Join [":",["arn:aws:sqs",!Ref Region, !Ref AccountID, !Join ["-", [!Ref QueueName, !Ref Environment]]]]
            